Repository Algo-Phantoms/Algo-ScriptML, pull requests merged in 2021-03, with the labels that each got.

#11 K-Means - Base
  K-Means/kmeans.py
Labels: Clear-M, Level 3, gssoc21

#64 Lasso_Regression - Base
  Lasso Regression/Lasso_Regression.py
  Lasso Regression/README.md
  Ridge Regression/README.md
Labels: Clear-M, Level 3, gssoc21

#78 Multilayer Perceptron- Documentation added
  Multilayer Perceptron/README.md
  Multilayer Perceptron/multi_layer_perceptron.jpg
  Multilayer Perceptron/multi_layer_perceptron2.jpg
Labels: Clear-M, Level 1, gssoc21

#83 Linear Regression - Documentation
  Linear Regression/README.md
Labels: Clear-M, Level 1, documentation, gssoc21

#84 Issue 58: K-Means algorithm - Documentation
  K-Means/README.md
Labels: Clear-M, Level 1, documentation, gssoc21

#45 Linear regression module added
  Linear Regression/Linear_Regression.py
  Linear Regression/README.md
Labels: Base, Clear-M, Level 3, gssoc21

#75 Bayesian Regression - Documentation
  Bayesian Regression/README.md
Labels: Clear-M, Level 1, documentation, gssoc21

#87 Logistic Regression - Documentation
  Logistic Regression/README.md
Labels: Clear-M, Level 1, documentation, gssoc21

#90 Decision Tree- Documentation
  Decision Tree/Decision_Tree.jpg
  Decision Tree/Decision_Tree.png
  Decision Tree/README.md
Labels: Clear-M, Level 1, documentation, gssoc21

#98 Issue #56 Random Forest Documentation
  Random Forest/README.md
Labels: Clear-M, Level 1, documentation, gssoc21

#53 Perceptron Issue #34
  Perceptron/README.md
  Perceptron/__pycache__/perceptron_training.cpython-38.pyc
  Perceptron/perceptron_test.py
  Perceptron/perceptron_training.py
Labels: Base, Clear-M, Level 3, gssoc21

#93 Ridge Regression-Base
  Ridge Regression/Ridge Regression- Base.py
Labels: Base, Clear-M, Level 3, gssoc21

#100 Apriori Base issue#36
  Apriori/GroceryStoreDataSet.csv
  Apriori/apriori.py
Labels: Base, Clear-M, Level 3, gssoc21

#102 Logistic regression - Base issue#38
  Logistic Regression/Logistic_Regression_base.py
Labels: Base, Clear-M, Level 3, Reviewed, gssoc21

#115 SVM - Documentation
  Support Vector Machine/README.md
Labels: Clear-M, Level 1, documentation, gssoc21

#112 PCA - Documentation
  Principal Component Analaysis/README.md
Labels: Level 1, Reviewed, documentation, gssoc21

#116 Stochastic Gradient Descent - Base and Documentation
  stochastic gradient descent/README.md
  stochastic gradient descent/stochastic_gradient_descent_algo.py
Labels: Clear-M, Level 3, gssoc21

#99 Adaboost-Base Issue#35
  Adaboost/Iris.csv
  Adaboost/adaboost_base_35.py
Labels: Base, Clear-M, Level 3, gssoc21

#118 added Naive Bayes -Documentation
  Naive Bayes/Naive Bayes.jpg
  Naive Bayes/README.md
Labels: Clear-M, Level 1, documentation, gssoc21
