Repository Algo-Phantoms/Algo-ScriptML, pull requests merged in 2021-04, with the labels that each got.

#128 Random Forest is added
  Random Forest/randomForest.py
  Random Forest/randomForestTest.py
Labels: Base, Clear-M, Level3, Under Review, gssoc21

#109 Elastic net - Base
  Elastic Net/Elastic_Net_Regression.py
  Elastic Net/Salary_Data.csv
Labels: Base, Clear-M, Level3, gssoc21

#162 Completed the documentation for Gaussian Mixture Model
  Gaussian Mixture Model/README.md
Labels: Level 1, gssoc21
