Repository Algo-Phantoms/Algo-ScriptML, pull requests merged in 2021-06, with the labels that each got.

#198 Elastic Net Regression - Documentation
  Elastic Net/README.md
Labels: Clear-M, Level1, documentation, gssoc21

#199 Lowess Regression - Documentation
  Lowess Regression/README.md
Labels: Clear-M, Level1, documentation, gssoc21

#203 Spectral Clustering - Documentation
  Spectral Clustering/README.md
Labels: Level1, gssoc21

#209 Spectral Clustering - Base
  Spectral Clustering/spectral_clustering.py
Labels: Base, Level3, gssoc21

#207 Mini Batch K-means Clustering - Documentation
  Mini Batch K-means Clustering/README.md
Labels: Level1, gssoc21

#208 XGBoost - Documentation
  XGBoost/README.md
Labels: Level1, gssoc21

#206 BIRCH Clustering - Documentation
  BIRCH Clustering/README.md
Labels: Level1, gssoc21

#192 Multiple Linear Regression - Base
  Multiple Linear Regression/multiple_linear_regression_implementation.py
Labels: Base, Level3, gssoc21

#200 Add Markov's Chain
  Markov's Chain/Markov's Chain
  Markov's Chain/Markov's-Chain.ipynb
  Markov's Chain/Markov's-Chain.py
  Markov's Chain/Trump-Speech.txt
Labels: Base, Level3, gssoc21

#95 DBSCAN - Base
  DBSCAN/dbscan.py
Labels: Base, enhancement, gssoc21
