Repository Algo-Phantoms/Algo-ScriptML, pull requests merged in 2021-05, with the labels that each got.

#175 Neural Network Update README.md
  Neural Network/README.md
Labels: Clear-M, Level 1, documentation, gssoc21

#140 [base] - added Normalization and Standardization class
  .gitignore
  Preprocessing/min_max_scaler.py
  Preprocessing/standard_scaler.py
Labels: Base, Level 2, Under Review, gssoc21

#152 LOWESS REGRESSION SOLUTION #33
  Lowess Regression/lowessregression.py
Labels: Base, Clear-M, Level 3, gssoc21

#103 Support Vector Machine Base issue#25
  Support Vector Machine/SVM_Linear_Kernal_&_documentation.py
Labels: Base, Level 3, Reviewed, gssoc21

#145 Hierarchical Clustering: Counting the number of clusters from dendrogram
  Hierarchical Clustering/README.md
  Hierarchical Clustering/implementation.py
Labels: Base, Level 3, gssoc21

#159 Adaboost - Documentation
  Adaboost/README.md
Labels: Clear-M, Level 1, documentation, gssoc21

#160 Update README.md KNN documentation
  K Nearest Neighbors/README.md
Labels: Clear-M, Level 1, documentation, gssoc21

#134 Added Hidden Markov Model
  .DS_Store
  Hidden Markov Model/.DS_Store
  Hidden Markov Model/README.md
  Hidden Markov Model/assets/initial.png
  Hidden Markov Model/assets/model.png
  Hidden Markov Model/assets/observation.png
  Hidden Markov Model/assets/state.png
  Hidden Markov Model/hmm.py
  Hidden Markov Model/main.py
  Hidden Markov Model/outputs/HMM.dot
  Hidden Markov Model/outputs/HMM.dot.png
Labels: Base, Level3, Under Review, gssoc21

#153 updated decision tree implementation
  Decision Tree/decision_tree_implementation.py
Labels: Base, Clear-M, Level3, gssoc21

#143 KNN Base model
  K Nearest Neighbors/k-nearest neighbors (KNN).py
Labels: Base, Level3, gssoc21

#150 Update README.md
  DBSCAN/README.md
Labels: Level1, documentation, gssoc21

#144 Bayesian Linear Regression
  Bayesian Regression/bayessian_regression.py
Labels: Base, Level3, gssoc21

#186 Completed the documentation for LDA
  Linear discriminant analysis/README.md
Labels: Clear-M, Level1, documentation, gssoc21

#189 Update README.md
  README.md
Labels: Level0, gssoc21

#190 README for Apriori Algorithm Added
  Apriori/README.md
Labels: Clear-M, Level1, documentation, gssoc21

#187 Add Genetic Algorithm
  Genetic Algorithm/README.md
Labels: Clear-M, Level1, gssoc21

#184 Naïve Bayes Algorithm Added
  Naive Bayes/naive_bayes.py
Labels: Clear-M, Level3, gssoc21

#194 FP Growth - Documentation
  FP-Growth/README.md
Labels: Level3, gssoc21

#188 Implemented Gaussian Mixture Model in python
  Gaussian Mixture Model/GaussianMixtureModel.py
Labels: Clear-M, Level3, gssoc21

#193 Multiple Linear Regression - Documentation
  Multiple Linear Regression/README.md
Labels: Level1, gssoc21
